src/main/java/org/apache/sysml/hops/ConvolutionOp.java, src/main/java/org/apache/sysml/runtime/instructions/gpu/ConvolutionGPUInstruction.java, src/main/java/org/apache/sysml/runtime/instructions/gpu/context/JCudaObject.java, src/main/java/org/apache/sysml/runtime/matrix/data/LibMatrixCUDA.java
- Fixed the timer that counts the number of times memory chunks are
zero-ed out
- Some minor code refactoring
@niketanpansare
=> [HOTFIX] Disabling GPU fused relu & maxpooling operator because of bug

README.md
[Minor] change build status image url to travis-ci
=> [MINOR] change build status image url

docs/algorithms-factorization-machines.md, docs/algorithms-reference.md
_what does this contain?_
1. model equation
2. little theoretical support
3. calculations as to how order of computation changed.
4. gradients
_what's later_
1. once @dusenberrymw reviews & merges classification & regression, documentation will be added for them also.
Thanks a lot.
=> [DOC] Factorization Machines core module

src/test/java/org/apache/sysml/test/integration/functions/codegenalg/AlgorithmPCA.java, src/test/scripts/functions/codegenalg/Algorithm_PCA.R
_what is here?_
A preliminary script only to test that dml will run. - as a first iteration.
=> [SYSTEMML-2121] PCA test for codegenalg suite

src/main/java/org/apache/sysds/api/DMLOptions.java
This PR is to test if the bug is fixed.
=> [SYSTEMDS-335] Fix bug in exposed eviction policy names

CONTRIBUTING.md
**What this PR do?**
1.  Provides more details license files.
2. Add new section for general guidelines
**TL;DR**
Add SystemDS team's thinking/working philosophy based on the PR/commit/mailing list activity.
=> Contributing guide inclusion of guidelines

src/test/java/org/apache/sysds/test/AutomatedTestBase.java, src/test/java/org/apache/sysds/test/functions/mlcontext/MLContextPageRankTest.java, src/test/java/org/apache/sysds/test/functions/mlcontext/MLContextTestBase.java
**What this PR do?**
Tests Page Rank with MLContext.
**TL;DR:**
=> [SYSTEMDS-2597] Verify PageRank script works with MLContext

dev/docs/dml-vs-r-guide.md
**What this PR do?**
1. some common differences between R and DML
2. The examples should be runnable to make the
guide more interesting.
**TL;DR:**
Keep the differences b/w `dml` and `R` in a well-lit place
=> [WIP][DOC] DML to R translation guide

dev/release/old-release-build.sh, dev/release/publish.sh, dev/release/svn_dev_upload.sh
PR to check if tests are passing.
=> [MINOR] Fix bugs in the release scripts

src/main/java/org/apache/sysds/runtime/compress/CompressedMatrixBlock.java, src/main/java/org/apache/sysds/runtime/compress/CompressedMatrixBlockFactory.java, src/main/java/org/apache/sysds/runtime/compress/CompressionSettingsBuilder.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroup.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupDDC.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupDDC1.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupDDC2.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupOLE.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupRLE.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupUncompressed.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupValue.java, src/main/java/org/apache/sysds/runtime/compress/utils/LinearAlgebraUtils.java, src/test/java/org/apache/sysds/test/TestUtils.java, src/test/java/org/apache/sysds/test/component/compress/CompressedTestBase.java, src/test/resources/log4j.properties
Fix bug in right multiplication OLE where the disabled skiplist would
break the execution, because it was disabled.
=> [MINOR] Fix OLE skipList

src/main/python/systemds/operator/algorithm.py, src/main/python/systemds/operator/operation_node.py, src/main/python/tests/matrix/test_binary_op.py
This commit add the left hand side ops to enable ops like:
3 > M
3 * M
furthermore this commit fixes a :bug: in transpose that did not set
shape correctly, and the same for matrix multiply.
=> [SYSTEMDS-2700] Python Left hand side ops

pom.xml, src/main/java/org/apache/sysds/common/Types.java, src/main/java/org/apache/sysds/runtime/controlprogram/caching/MatrixObject.java, src/main/java/org/apache/sysds/runtime/controlprogram/federated/FederatedData.java, src/main/java/org/apache/sysds/runtime/controlprogram/federated/FederationMap.java, src/main/java/org/apache/sysds/runtime/instructions/fed/InitFEDInstruction.java, src/main/java/org/apache/sysds/runtime/io/ReaderWriterFederated.java, src/test/java/org/apache/sysds/test/AutomatedTestBase.java, src/test/java/org/apache/sysds/test/functions/federated/FederatedTestObjectConstructor.java, src/test/java/org/apache/sysds/test/functions/federated/io/FederatedReaderTest.java, src/test/scripts/functions/federated/io/FederatedReaderTest.dml, src/test/scripts/functions/federated/io/FederatedReaderTestColReference.dml, src/test/scripts/functions/federated/io/FederatedReaderTestRowReference.dml
Read federated Matrices from file:
Layout:
```json
{
"[0, 0] - [5, 13]": {
"filepath": "target/testTemp/functions/federated/io/FederatedReaderTest/in/X1",
"dataType": "MATRIX",
"address": "localhost:42441"
},
"[5, 0] - [10, 13]": {
"filepath": "target/testTemp/functions/federated/io/FederatedReaderTest/in/X2",
"dataType": "MATRIX",
"address": "localhost:36989"
}
}
```
Metadata:
```json
{
"data_type": "matrix",
"value_type": "double",
"rows": 10,
"cols": 13,
"nnz": -1,
"format": "federated",
"author": "baunsgaard",
"created": "2020-10-25 18:55:02 CET"
}
```
=> Federated Read

.github/workflows/applicationTests.yml, .github/workflows/functionsTests.yml
Merge all the functions and application tests in one run.
=> Merged Tests

scripts/builtin/split.dml, src/test/java/org/apache/sysds/test/functions/builtin/BuiltinSplitTest.java, src/test/java/org/apache/sysds/test/functions/federated/primitives/FederatedMultiplyTest.java, src/test/java/org/apache/sysds/test/functions/federated/primitives/FederatedSplitTest.java, src/test/scripts/functions/builtin/split.dml, src/test/scripts/functions/federated/FederatedSplitTest.dml, src/test/scripts/functions/federated/FederatedSplitTestReference.dml
Added tests (builtin and federated) for new split builtin.
I don't understand that it is working with right indexing on the federated outputs but it seems to.
=> [SYSTEMDS-2722] Split Testing

src/main/java/org/apache/sysds/runtime/controlprogram/caching/CacheableData.java, src/main/java/org/apache/sysds/runtime/controlprogram/federated/FederationMap.java, src/main/java/org/apache/sysds/runtime/instructions/fed/AggregateBinaryFEDInstruction.java, src/main/java/org/apache/sysds/runtime/instructions/fed/InitFEDInstruction.java, src/test/java/org/apache/sysds/test/functions/federated/algorithms/FederatedYL2SVMTest.java, src/test/java/org/apache/sysds/test/functions/federated/primitives/FederatedNegativeTest.java
I hope these changes don't overlap to much with yours @mboehm7
=> [MINOR] Federated Type Fixes

src/main/java/org/apache/sysds/runtime/compress/lib/LibRightMultBy.java
This commit revisits 2614 that introduced compressed right matrix multiplication.
with the minor changes in this commit to correctly use threadLocal
memory, and better blocks for decompression in a right matrix
multiplication the performance (depending on data characteristics and
system) becomes 2-8x faster for the compressed operation, meaning that
if there is co-coding of columns the operation is equal or up to 6x
faster than our default right matrix multiplication.
=> [SYSTEMDS-2614] Compressed Right Matrix Multiplication

src/main/java/org/apache/sysds/runtime/data/DenseBlock.java, src/main/java/org/apache/sysds/runtime/matrix/data/LibMatrixReorg.java, src/main/java/org/apache/sysds/runtime/matrix/data/MatrixBlock.java, src/test/java/org/apache/sysds/test/component/matrix/TransposeInplaceTest.java
This commit adds a function to our Lib MatrixReorg containing a way
to transpose in place a dense matrix block. (single threaded for now)
The implementation is based on:
A  Decomposition  for  In-place  Matrix  Transposition
by Bryan Catanzaro et al. PPoPP 2014
=> [SYSTEMDS-2761] Transpose in place

scripts/aws/README.md, scripts/aws/spinup_systemds_cluster.sh, scripts/aws/systemds_cluster.config
1. Update script to avoid name conflicts
2. Add clear docs for Administrator setup and user setup
=> [SYSTEMDS-2926] Clarify AWS README and update bucket name conflict

docs/site/dml-vs-r-guide.md
- Removing duplicates
- Sparse matrix representation
- Indexing operations
=> [DOC] DML recipes for operations over matrices

docs/site/dml-vs-r-guide.md
- the list of distinct categories
- the maximum value for each category
- 0-1 aggregation matrix that adds records of the same category
=> [DOC] Group by aggregate using linear algebra usage

docs/site/dml-vs-r-guide.md
Inverse lower triangular matrix with divide-and-conquer approach.
=> [SYSTEMDS-2968] DML recipes for common algorithms

scripts/staging/google-cloud/README.md
Provides a workspace to start prototyping on Google Cloud.
=> Preliminary instructions to run an example spark job

notebooks/systemds_dev.ipynb
* Add permalinks for the haberman.data
* Use the latest spark 2.4.7 version
* Make sure the content is fresh and relevant.
=> [MINOR] Update broken links, version names

docs/site/builtins-reference.md
Add documentation for KNN.
Companion for https://github.com/apache/systemds/commit/ad899416d3d583df9bf4c6c16755e0bd39382385
=> [SYSTEMDS-2869][DOC] Built-in functions KNN and KNNBF

docs/site/builtins-reference.md
References: https://github.com/apache/systemds/pull/1153
=> [SYSTEMDS-2891][DOC] Gaussian classifier builtin

docs/site/builtins-reference.md
Reference algorithm:
https://en.wikipedia.org/wiki/Spline_interpolation#Algorithm_to_find_the_interpolating_cubic_spline
Implementation:
https://github.com/apache/systemds/commit/58ec5030ecbc24c27a771ef9535f1697c1d60fa6
=> [SYSTEMDS-2842][DOC] cspline builtin doc

notebooks/databricks/MLContext.scala, notebooks/databricks/README.md
Make sure the instructions are up-to-date. Run the notebook and check.
some useful references:
https://docs.databricks.com/notebooks/notebooks-manage.html
=> SystemDS on Databricks notebook update

notebooks/databricks/MLContext.scala
Dataset look:
Training loss: (The values look unreasonable, though)
| __INDEX | C1 |
|-|-|
| 1 | 17420.281879396196 |
| 2 | 16703.278427261495 |
| 3 | 15287.173372263424 |
| 4 | 13747.924068494714 |
| 5 | 12659.174474311716 |
| 6 | 12020.593726191319 |
| 7 | 11623.463623079939 |
| 8 | 11377.749847684645 |
| 9 | 11229.421778277296 |
| 10 | 11135.985988427841 |
| ... | ... |
Data source: https://snap.stanford.edu/data/amazon0601.html
=> Amazon coproduct purchasing network, PNMF and SystemDS

docs/site/gpu.md
Discussion: 
http://mail-archives.apache.org/mod_mbox/systemds-dev/202105.mbox/%3CCAObMueUEf4JMeuzUhU0G%3DansUFojH6gXGNaxg1t5fwffW6iZRw%40mail.gmail.com%3E
=> [SYSTEMDS-2970] Guide running SystemDS with GPU

docs/site/builtins-reference.md
=> [SYSTEMDS-2870][DOC] Builtin Decision Tree

docs/_includes/header.html, docs/site/gpu.md
* initial  linux instructions
* add GPU brand version support
* Update gpu.md
* fix format add libcudnn instructions
* add single node invocation command
=> [SYSTEMDS-2970] Initial linux instructions for GPU

docs/site/builtins-reference.md
We might need to use a linter in the future! 😃
=> [MINOR] fix rendering of tables, use space after headers

docs/site/builtins-reference.md
Also, uses spaces after headers consistently.
This is a followup to https://github.com/apache/systemds/commit/5f23666d50a7f70123e23c0e4e8c9d32d0c639d4
=> [MINOR] Arrange Builtin functions in the alphabetical order

dev/release/pypi_upload.sh
**Usage instruction:**
```sh
$ systemds > ./dev/release/pypi_upload.sh
```
minimize variables, add further documentation and check for the artifacts.
Published test artifacts at https://test.pypi.org/project/systemds/2.1.0rc6/
=> Pypi publish script

CONTRIBUTING.md
Refer: https://s.apache.org/supported-commit-tags
=> [MINOR][DOC] add multiple jira tag instructions

docs/updateAPI.sh
.
---
Fixes https://github.com/j143/systemds/issues/178
=> [MINOR] Robust check for _images folder and set -e flag

docs/README.md
=> [DOCS] updateAPI.sh usage requirements and instructions

.github/workflows/applicationTests.yml, .github/workflows/build.yml, .github/workflows/componentTests.yml, .github/workflows/documentation.yml, .github/workflows/federatedPython.yml, .github/workflows/functionsTests.yml, .github/workflows/python.yml
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths
=> [SYSTEMDS-3053] Do not run Action workflow for doc changes

docs/_includes/header.html, docs/site/native-backend.md
Enabling Native BLAS on SystemDS instructions
=> [SYSTEMDS-3051] native blas guide

scripts/builtin/bandit.dml, scripts/builtin/executePipeline.dml, scripts/builtin/topk_cleaning.dml, scripts/pipelines/scripts/enumerateLogical.dml, scripts/pipelines/scripts/utils.dml, src/test/java/org/apache/sysds/test/functions/pipelines/BuiltinTopkCleaningClassificationTest.java, src/test/java/org/apache/sysds/test/functions/pipelines/BuiltinTopkCleaningRegressionTest.java, src/test/java/org/apache/sysds/test/functions/pipelines/BuiltinTopkLogicalTest.java, src/test/scripts/functions/pipelines/topkLogicalTest.dml, src/test/scripts/functions/pipelines/topkcleaningClassificationTest.dml, src/test/scripts/functions/pipelines/topkcleaningRegressionTest.dml
- Train and test data parameters are added into topk_cleaning builtin
- Holdout test case is added to avoid data leakage problem in evaluation
- TODO fix the cross validations to avoid any possible data leakage
=> [MINOR] Cleaning Pipelines - Holdout test added

.asf.yaml, .github/workflows/applicationTests.yml, .github/workflows/build.yml, .github/workflows/componentTests.yml, .github/workflows/documentation.yml, .github/workflows/functionsTests.yml, .github/workflows/python.yml, README.md, docker/testsysds.Dockerfile, docs/_includes/header.html, docs/api/python/sources/guide/federated.rst.txt, docs/css/bootstrap.min.css, docs/index.md, docs/site/algorithms-factorization-machines.md, docs/site/windows-source-installation.md, pom.xml, scripts/staging/google-cloud/README.md, scripts/staging/onnx/onnx_systemds/README.md, scripts/staging/onnx/onnx_systemds_docs/onnx_systemds.rst, scripts/staging/onnx/onnx_systemds_docs/onnx_systemds_design.rst, src/assembly/bin/README.md, src/main/python/docs/source/guide/federated.rst
Include changes relevant when rename our dev branch to `main`.
=> [SYSTEMDS-2599] Development branch name change to main

docs/_config.yml
=> [MINOR] Update docs to `2.3.0-SNAPSHOT`

.asf.yaml, README.md, docs/api/python/sources/index.rst.txt, pom.xml, src/main/python/setup.py
as per the https://s.apache.org/systemds-3011-mail-discussion
agreed candidate:
```md
Apache SystemDS - An open source ML system for the end-to-end data science lifecycle
```
=> [Systemds 3011] Project description to reflect the present scope

pom.xml
fixes
https://github.com/junit-team/junit4/security/advisories/GHSA-269g-pwp5-87pp
=> [MINOR] Upgrade junit version to 4.13.2

.github/workflows/python.yml, src/main/python/systemds/context/systemds_context.py, src/main/python/systemds/operator/nodes/list.py, src/main/python/systemds/operator/nodes/scalar.py, src/main/python/systemds/script_building/script.py, src/main/python/tests/script/test_dml_script.py, src/main/python/tests/source/source_with_list_input.dml, src/main/python/tests/source/test_source_list.py
This commit fixes a bug where the sourced functions would not
correctly build the scripts in cases where a list is an input to the
function defined in a sourced script.
=> [SYSTEMDS-3223] Python functions with list arguments

docker/pythonsysds.Dockerfile, docker/sysds.Dockerfile
Let us not merge, this.
of course, changes are no way connected
The tests in the `functions.lineage.**`, `functions.federated.**` pass/fail when run different times. (locally)
https://github.com/apache/systemds/runs/4316289297?check_suite_focus=true
=> reverse last #1465 to see the tests pass

src/test/java/org/apache/sysds/test/gpu/BuiltinUnaryGPUInstructionTest.java
=> [MINOR] Fix imports in BuiltinUnaryGPUInstructionTest

dev/release/pypi-upload.sh
as per the version scheme introduced in this commit https://github.com/apache/systemds/commit/2c90f9e7009d766ed0cb887d4f319c54c322e410
=> [MINOR] Update Python version info to `x.y.z-dev` in pypi-upload script

docs/site/builtins-reference.md, scripts/builtin/xgboost.dml
`y` parameter is not consistent across all the files. :)
=> [MINOR][DOC] xgboost function y parameter correct usage

dev/release/create-tag.sh, dev/release/release-build.sh
and remove redundant and commented code
=> keep release scripts concise

dev/release/src/test/bin/verifyBuild.sh
=> [MINOR] fix release build verify script

src/main/python/setup.py, src/main/python/systemds/project_info.py
.
version for the main: 3.1.0-dev
=> [DOC] Update python api project description and version

docs/_config.yml, src/main/python/docs/source/conf.py
=> [MINOR] Update project version in docs

.github/workflows/docker-release.yml
=> [SYSTEMDS-3401] Release docker images with GitHub actions

.github/workflows/docker-release.yml
https://github.com/docker/build-push-action#customizing
=> [MINOR] Add latest tag to docker image

src/main/java/org/apache/sysds/runtime/compress/estim/sample/HassAndStokes.java, src/main/java/org/apache/sysds/runtime/compress/estim/sample/SampleEstimatorFactory.java, src/main/java/org/apache/sysds/runtime/compress/estim/sample/ShlosserEstimator.java, src/main/java/org/apache/sysds/runtime/compress/estim/sample/ShlosserJackknifeEstimator.java, src/main/java/org/apache/sysds/runtime/compress/estim/sample/SmoothedJackknifeEstimator.java, src/test/java/org/apache/sysds/test/component/compress/estim/SampleDistinctTest.java
Minor test and cleanup in sample estimators
#1664
=> [MINOR] shlosserEstimator update and fix

.github/workflows/monitoringUITests.yml
Basic test: angular app builds without any issues.
=> [SYSTEMDS-3422] Add monitoring tool testing workflows

dev/release/check-release-machine.py
=> [WIP] script to check the release machine requirements

docs/site/Release-Process.md, docs/site/release-process.md
complete release process details - first draft.
=> [SYSTEMDS-3187] Add documentation for the release process

.github/workflows/release-scripts.yml, dev/release/do-release.sh, dev/release/release-utils.sh
* Confidence check that the shell scripts used for release, won't break.
* maven release related plugins work as intended.
=> [SYSTEMDS-3480] Verify release scripts with github workflows

src/main/java/org/apache/sysds/runtime/frame/data/compress/FrameCompressionStatistics.java, src/main/java/org/apache/sysds/runtime/frame/data/lib/FrameLibCompress.java, src/main/java/org/apache/sysds/runtime/instructions/cp/CompressionCPInstruction.java
also include compression cp instruction on frame.
=> Transform Encode compress 

.github/workflows/build.yml
try to make windows build parse
=> [MINOR] Windows action try out

src/main/java/org/apache/sysds/runtime/instructions/OOCInstructionParser.java, src/main/java/org/apache/sysds/runtime/instructions/ooc/OOCInstruction.java, src/main/java/org/apache/sysds/runtime/instructions/ooc/TransposeOOCInstruction.java, src/test/java/org/apache/sysds/test/functions/ooc/TransposeTest.java, src/test/scripts/functions/ooc/Transpose.dml
=> [SYSTEMDS-3911] OOC Transpose operation
