apache/systemds

src/main/java/org/apache/sysds/runtime/instructions/InstructionUtils.java, src/main/java/org/apache/sysds/runtime/instructions/cp/DataGenCPInstruction.java, src/main/java/org/apache/sysds/runtime/lineage/LineageCache.java, src/main/java/org/apache/sysds/runtime/lineage/LineageCacheConfig.java, src/main/java/org/apache/sysds/runtime/lineage/LineageCacheEviction.java, src/main/java/org/apache/sysds/runtime/lineage/LineageCacheStatistics.java, src/main/java/org/apache/sysds/runtime/lineage/LineageRewriteReuse.java, src/main/java/org/apache/sysds/utils/Statistics.java, src/test/scripts/functions/lineage/LineageReuseAlg2.dml, src/test/scripts/functions/lineage/RewriteTest3.dml
This patch
- extends reusable opcodes, which primarily improves multilevel (statementblock) cache hits,
- removes most of the System.nanoTime calls from cache logic,
- replaces operand names with placeholders in datagen lineage items,
(Note: this fix is temporarily commented due to a bug in parfor-lineage)
- fixes a bug in lineage item creation for multilevel caching,
- update grid search lineage test with a loss function.
=> [MINOR] Extend reusable instructions and bug fixes

dev/docs/Tasks.txt, src/main/java/org/apache/sysds/runtime/instructions/cp/MultiReturnBuiltinCPInstruction.java, src/main/java/org/apache/sysds/runtime/lineage/LineageCache.java, src/main/java/org/apache/sysds/runtime/lineage/LineageCacheConfig.java, src/main/java/org/apache/sysds/runtime/lineage/LineageRewriteReuse.java, src/test/java/org/apache/sysds/test/functions/lineage/LineageReuseAlg.java, src/test/scripts/functions/lineage/LineageReuseAlg4.dml
This patch enables caching of multi-return instructions like eigen.
Furthermore, this includes a new partial rewrite and adds PCA
as a test case.
=> [SYSTEMDS-413] Cache MultiReturnBuiltin instructions

dev/Tasks.txt, src/main/java/org/apache/sysds/runtime/lineage/LineageRewriteReuse.java, src/test/java/org/apache/sysds/test/functions/lineage/LineageReuseAlg.java, src/test/scripts/functions/lineage/LineageReuseAlg6.dml
This patch contains a rewrite to reuse tsmm result in lmDS if
called after PCA incrementally for increasing number of columns.
=> [SYSTEMDS-414] New rewrite for PCA -> lmDS pipeline

src/test/java/org/apache/sysds/test/AutomatedTestBase.java, src/test/java/org/apache/sysds/test/functions/mlcontext/MLContextLinregTest.java
* Takes advantage of existing R algorithm scripts used for
codegen testing.
* This would improve the testing by allowing us to provide all
the necessary inputs into the script.
=> [SYSTEMDS-1863] Full MLContext test for LinearReg

.github/workflows/componentTests.yml, docker/entrypoint.sh, pom.xml
This commit changes the Pom file to not execute any of the test steps
while building the project per default.
to enable tests use the flag '-D maven.test.skip=false'.
to enable code coverage use also the flag '-D jacoco..skip=false'
As a nice bonus, the time to package the project is reduced by ~50%
=> [MINOR] Fix POM for jacoco skipping

src/main/java/org/apache/sysds/api/DMLScript.java, src/test/java/org/apache/sysds/test/AutomatedTestBase.java
This PR change the output for a user to not print the stack trace in case of an exception or stop has been called.
example script:
```R
x = 0
for(i in 1:10){
if(i > 4){
stop("I is to high")
}
x = x + i
}
print(x)
```
Before terminal:
```bash
Me:../secret$ ./run.sh 
Using existing SystemDS at ../../../systemds
SystemDS Statistics:
Total execution time:           0.003 sec.
Exception in thread "main" org.apache.sysds.runtime.DMLScriptException: I is to high
at org.apache.sysds.runtime.instructions.cp.UnaryScalarCPInstruction.processInstruction(UnaryScalarCPInstruction.java:59)
at org.apache.sysds.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:247)
at org.apache.sysds.runtime.controlprogram.ProgramBlock.executeInstructions(ProgramBlock.java:204)
at …
```
=> [MINOR] Usability Stack trace

src/main/java/org/apache/sysds/api/DMLScript.java, src/main/java/org/apache/sysds/conf/DMLConfig.java, src/main/java/org/apache/sysds/runtime/controlprogram/federated/FederatedData.java, src/main/java/org/apache/sysds/runtime/controlprogram/federated/FederatedWorker.java, src/test/java/org/apache/sysds/test/functions/federated/io/FederatedSSLTest.java, src/test/scripts/functions/federated/io/SSLConfig.xml
Using a self signed SSL certificate, the communication using Netty becomes encrypted.
The initialization of the communication is not safe since anyone could construct a certificate on the server side (workers) and respond to the requests from the controller. But for an initial prototype it is fine.
To allow all communication to be valid anyway, the certificate is self signed, and trusted at the beginning. It is fine since we know that it is generated specifically for the communication we want from the federated site. And allows for encrypted answers to the controller.
=> [SYSTEMDS-2721] Add Federated SSL

pom.xml, src/main/java/org/apache/sysds/runtime/compress/BitmapEncoder.java, src/main/java/org/apache/sysds/runtime/compress/CompressedMatrixBlock.java, src/main/java/org/apache/sysds/runtime/compress/ReaderColumnSelectionBitSet.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroup.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupConst.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupDDC.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupOLE.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupOffset.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupRLE.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupUncompressed.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupValue.java, src/main/java/org/apache/sysds/runtime/compress/lib/LibRelationalOp.java, src/main/java/org/apache/sysds/runtime/instructions/InstructionUtils.java, src/test/java/org/apache/sysds/test/component/compress/CompressedTestBase.java
This commit adds relational support for relational operations,
(< > <= etc) in the compressed space, for overlapping matrices.
If the relational expression returns a constant matrix, the operations
are super fast, while if the output is mixed it performs equally to our
uncompressed. Further optimizations are available, but since this
operation is not critical it is not explored yet.
nNmbers are in in ms avg.
cla     ,    0.1700  constant output
lcla    ,    0.0700  constant output
mkl     ,    1.2300  constant output
cla     ,   43.7400  Normal Perfomance
lcla    ,   43.9900  Normal Perfomance
mkl     ,   47.8400  Normal Perfomance
=> [SYSTEMDS-2696] Overlapping relational operations

pom.xml, src/main/java/org/apache/sysds/runtime/compress/CompressedMatrixBlock.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupConst.java, src/main/java/org/apache/sysds/runtime/compress/lib/LibCompAgg.java, src/main/java/org/apache/sysds/runtime/compress/lib/LibLeftMultBy.java, src/main/java/org/apache/sysds/runtime/compress/lib/LibRelationalOp.java, src/main/java/org/apache/sysds/runtime/compress/lib/LibRightMultBy.java, src/test/java/org/apache/sysds/test/component/compress/AbstractCompressedUnaryTests.java, src/test/java/org/apache/sysds/test/component/compress/CompressedMatrixTest.java, src/test/java/org/apache/sysds/test/component/compress/CompressedTestBase.java
This commit add the functionality to do unary aggregates on the compressed overlapping matrices
=> [SYSTEMDS-2741] Compressed overlapping unary aggregates 

scripts/builtin/pca.dml, scripts/builtin/pcaInverse.dml, scripts/builtin/pcaTransform.dml, scripts/builtin/scale.dml, src/main/java/org/apache/sysds/common/Builtins.java, src/test/java/org/apache/sysds/test/functions/federated/algorithms/FederatedPCATest.java, src/test/scripts/functions/federated/FederatedPCATest.dml, src/test/scripts/functions/federated/FederatedPCATestReference.dml
Adds a predict function for PCA and an inverse function.
The predict is for unseen data, that the PCA was not trained for just like our other predict functions for other algorithms
The Inverse is to apply on an PCA reduced dataset, to reconstruct an approximation of the original data.
The second is added because PCA can be considered a classic Lossy compression algorithm, that gives an smaller, approximated matrix of the original data. It also allows us to calculate how well the given PCA fits to the dateset.
=> [SYSTEMDS-2757] PCA Predict and Inverse

src/main/java/org/apache/sysds/conf/DMLConfig.java, src/main/java/org/apache/sysds/runtime/compress/CompressedMatrixBlock.java, src/main/java/org/apache/sysds/runtime/compress/CompressedMatrixBlockFactory.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroup.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupConst.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupDDC.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupDDC1.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupDDC2.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupOLE.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupRLE.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupUncompressed.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupValue.java, src/main/java/org/apache/sysds/runtime/compress/estim/CompressedSizeEstimatorFactory.java, src/main/java/org/apache/sysds/runtime/compress/lib/LibBinaryCellOp.java, src/main/java/org/apache/sysds/runtime/compress/lib/LibCompAgg.java, src/main/java/org/apache/sysds/runtime/compress/lib/LibLeftMultBy.java, src/main/java/org/apache/sysds/runtime/compress/lib/LibRelationalOp.java, src/main/java/org/apache/sysds/runtime/compress/lib/LibRightMultBy.java, src/main/java/org/apache/sysds/runtime/compress/lib/LibScalar.java, src/main/java/org/apache/sysds/runtime/compress/utils/LinearAlgebraUtils.java, src/main/java/org/apache/sysds/runtime/matrix/data/LibMatrixBincell.java, src/main/java/org/apache/sysds/runtime/matrix/data/MatrixBlock.java, src/test/java/org/apache/sysds/test/TestUtils.java, src/test/java/org/apache/sysds/test/component/compress/AbstractCompressedUnaryTests.java, src/test/java/org/apache/sysds/test/component/compress/CompressedTestBase.java, src/test/java/org/apache/sysds/test/component/compress/InvalidInputTest.java, src/test/java/org/apache/sysds/test/component/compress/ParCompressedMatrixTest.java, src/test/java/org/apache/sysds/test/component/compress/colgroup/JolEstimateTest.java
This commit change the Overlapping matrix to drastically reduce decompression time in cases of right hand side sparse matrix multiplication.
Other than this many of the methods are cleaned up, and isolated behind cleaner APIs for specific operations on Compressed Matrices.
=> [SYSTEMDS-2792] Sparse Overlapping Matrix

pom.xml, src/main/java/org/apache/sysds/common/Builtins.java, src/main/java/org/apache/sysds/common/Types.java, src/main/java/org/apache/sysds/hops/OptimizerUtils.java, src/main/java/org/apache/sysds/hops/UnaryOp.java, src/main/java/org/apache/sysds/parser/BuiltinFunctionExpression.java, src/main/java/org/apache/sysds/parser/DMLTranslator.java, src/test/java/org/apache/sysds/test/functions/compress/compressInstruction.java, src/test/java/org/apache/sysds/test/functions/compress/configuration/CompressBase.java, src/test/java/org/apache/sysds/test/functions/compress/configuration/CompressCost.java, src/test/java/org/apache/sysds/test/functions/compress/configuration/CompressForce.java, src/test/java/org/apache/sysds/test/functions/compress/configuration/CompressLossy.java, src/test/java/org/apache/sysds/test/functions/compress/configuration/CompressLossyCost.java, src/test/scripts/functions/compress/compressInstruction/compress_01.dml, src/test/scripts/functions/compress/compressInstruction/compress_02.dml
Dedicated script level functions to compress and decompress a matrix.
Currently i have hidden these behind a compile time boolean, that allows the introduction of these commands.
Unfortunately, since it is a compile time flag, the tests added would fail if set to false which is what we want in the end.
If someone have an idea in witch i can achieve:
1. The instructions are not allowed per default.
2. The instructions are allowed for tests.
3. The instructions are allowed if actively enabled.
I'm considering adding it as an Variable in our DMLConfig, but this just increase the number of parameters there.
=> [SYSTEMDS-2798] Builtin (de)compress function 

src/main/java/org/apache/sysds/runtime/controlprogram/federated/FederatedWorkerHandler.java, src/main/java/org/apache/sysds/runtime/instructions/fed/ReorgFEDInstruction.java, src/main/java/org/apache/sysds/runtime/lineage/LineageCache.java, src/main/java/org/apache/sysds/runtime/lineage/LineageCacheConfig.java, src/main/java/org/apache/sysds/runtime/lineage/LineageItemUtils.java, src/test/java/org/apache/sysds/test/functions/lineage/LineageFedReuseAlg.java, src/test/scripts/functions/lineage/FedLmPipelineReuse.dml
This patch handles reusing those UDFs that return metadata
with federated SUCCESS response (e.g. Rdiag, DiagMatrix).
Furthermore, this adds a test to reuse a full federated
pipeline having tasks such as preprocessing and
hyperparameter tuning (LM).
=> [SYSTEMDS-2799] Update UDF reuse, add Fed pipeline reuse test

pom.xml
This update is done because some tests sometimes crash with
"The forked VM terminated without properly saying goodbye".
This update seems to resolve this issue.
=> [MINOR] Surefire update to version 3.0.0-M5

docs/site/dml-vs-r-guide.md
Generally used for efficient calculation with the help of
momentum as discussed at https://cs.stackexchange.com/a/73760
--
For people familiar with python
```py
import numpy as np
data = np.array([2, 3, 0, 0, 4, 3], dtype=float)
result = []
last_value = 0
for d in data:
last_value = (last_value + d)*.95 # apply decay=0.95
result.append(last_value)
```
Related discussion as to how to cumsum with decay with:
NumPy - https://stackoverflow.com/q/28915088
Tensorflow 2.0 - https://stackoverflow.com/a/60635516
R - https://stackoverflow.com/q/14814752
=> [SYSTEMDS-2968] Cumulative sum with decay multiplier

docs/site/builtins-reference.md
Background:
Due to the accuracy oriented design of the classifiers the performance is
hindered with imbalance, which usually overlooks minority class.
"Any dataset with an unequal class distribution is technically imbalanced...
However a significant ... disproportion among the number of examples of each
class of the problem."
Page 19, section 2.1
source: https://www.springer.com/gp/book/9783319980737
Similar function implemented elsewhere:
Scikit learn -
http://glemaitre.github.io/imbalanced-learn/generated/imblearn.under_sampling.TomekLinks.html
R docs - https://www.rdocumentation.org/packages/UBL/versions/0.0.6/topics/TomekClassif
=> [SYSTEMDS-2877][DOC] Tomeklink builtin function

docs/site/install.md
Installing the openjdk-8 does not (sometimes!) update the pre-existing java installation.
```console
$ sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java to provide /usr/bin/java (java) in manual mode
```
=> [MINOR][DOC] update preexisting java command to openjdk8

NOTICE, src/assembly/bin/NOTICE, src/assembly/extra/NOTICE, src/main/python/docs/source/conf.py
as per:
https://github.com/apache/systemds/search?p=1&q=2020
This PR is to pin all the files where year update is required.
Note:
If you would like to add any more files, update directly in https://github.com/j143/systemds/tree/copyright-year (maintainer access!)
=> Copyright year update

dev/release/src/test/java/org/apache/sysds/validation/ValidateLicAndNotice.java, src/assembly/extra/LICENSE
All mentions of Caffe is removed from the license since caffe is
no longer used in systemds.
=> [SYSTEMDS-2570] Remove mentions of caffe in license

src/main/python/systemds/operator/nodes/source.py, src/main/python/systemds/script_building/dag.py, src/main/python/systemds/script_building/script.py, src/main/python/tests/source/test_source_reuse.py
This commit fix a bug in python source where if the source is used in multiple compute statements it breaks.
This is partially because the source command worked differently than other nodes. This commit now unifies this,
to a single way, and fixes the bug.
We should include this in the release.
=> [SYSTEMDS-3021] Python Source reuse fix

pom.xml
**What happens with this plugin?**
This plugin would only produce `.asc` files only.
- More about the plugin:
https://maven.apache.org/plugins/maven-gpg-plugin/plugin-info.html
---
**How maven signs artifacts with checksums?**
The following is about Maven Resolver (part of `maven core`)
- With version 1.6, it is not possible to sign artifacts with SHA-256 or higher
using
```sh
mvn -P'distribution' deploy -Daether.checksums.algorithms=SHA-256
```
- The signing with SHA512 
https://issues.apache.org/jira/browse/MPOM-118
because, the SHA-512 functionality has been added recently
---
Issues related to gpg-signing elsewhere:
https://github.com/j143/systemds/issues/99
=> [MINOR] maven-gpg-plugin update to version 3.0.1

src/main/java/org/apache/sysds/runtime/compress/CompressedMatrixBlock.java, src/main/java/org/apache/sysds/runtime/compress/lib/CLALibBinaryCellOp.java, src/main/java/org/apache/sysds/runtime/matrix/data/LibMatrixBincell.java, src/test/java/org/apache/sysds/test/functions/compress/workload/WorkloadAlgorithmTest.java, src/test/scripts/functions/compress/workload/WorkloadAnalysisLm.dml, src/test/scripts/functions/compress/workload/WorkloadAnalysisMLogReg.dml, src/test/scripts/functions/compress/workload/WorkloadAnalysisPCA.dml
The Binary element wise operation is sided, meaning that the inplace
operator needs to support witch input matrix to allocated the output into
wile taking into account which matrix the input cell is from.
This lead to a bug where the lef sided minus operator with an uncompressed
left matrix and compressed right would swap places in the execution and
therefore produce incorrect results.
The fix was to introduce a LeftBinary inplace operator in LibMatrixBincell.
=> [SYSTEMDS-2615] CLA BinaryCell operation fix

dev/release/release-to-svn.sh, dev/release/svn-staging-to-release.sh
Usage:
<details>
<summary><code>~/repo/systemds$ ./dev/release/release-to-svn.sh -n</code> </summary>
```console
ubuntu@ip-10-0-0-5:~/repo/systemds$ ./dev/release/release-to-svn.sh -n
RELEASE_VERSION : 2.2.0
APPROVED_RELEASE_TAG : 2.2.0-rc1
~/repo/systemds/systemds-repo-tmp-ZQWlk ~/repo/systemds
Checked out revision 50697.
Updating '2.2.0-rc1':
A    2.2.0-rc1
A    2.2.0-rc1/systemds-2.2.0-bin.tgz
A    2.2.0-rc1/systemds-2.2.0-bin.tgz.asc
A    2.2.0-rc1/systemds-2.2.0-bin.tgz.md5
A    2.2.0-rc1/systemds-2.2.0-bin.tgz.sha1
A    2.2.0-rc1/systemds-2.2.0-bin.tgz.sha512
A    2.2.0-rc1/systemds-2.2.0-bin.zip
A    2.2.0-rc1/systemds-2.2.0-bin.zip.asc
A    2.2.0-rc1/systemds-2.2.0-bin.zip.md5
A    2.2.0-rc1/systemds-2.2.0-bin.zip.sha1
A    2.2.0-rc1/systemds-2.2.0-bin.zip.sha512
A …
```
=> [SYSTEMDS-3193] Promote svn repo `dev/systemds/2.x-rc` to `release/systemds/2.x`

.github/workflows/applicationTests.yml, .github/workflows/build.yml, .github/workflows/componentTests.yml, .github/workflows/documentation.yml, .github/workflows/functionsTests.yml, .github/workflows/python.yml
```yml
on:
push:
paths-ignore:
- 'docs/**'
- '*.md'
- '*.html'
- 'src/main/python/docs/**'
- 'dev/**'
```
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths
=> [SYSTEMDS-3190] Do not run workflow for empty checks

pom.xml, src/assembly/bin.xml
**resources:**
[1] https://maven.apache.org/guides/mini/guide-reproducible-builds.html
[2] https://lists.apache.org/thread/9wk97dwjlcoxlk1onxotfo8k98b2v0sk
[3] https://github.com/apache/maven-apache-parent/compare/apache-18...apache-24#diff
Following apache projects 😺 
https://github.com/apache/zeppelin/pull/3930
https://github.com/apache/drill/pull/2360
https://github.com/apache/flink/pull/17005
=> [SYSTEMDS-3196] Update `org.apache` parent pom version to 24

dev/release/pypi-upload.sh, src/main/python/pre_setup.py
```python
>>> regex1 = fnmatch.translate('systemds-*-bin.zip')
>>> regex1
'(?s:systemds\\-.*\\-bin\\.zip)\\Z'
>>> resobj1 = re.compile(regex1)
>>> resobj1.match('systemds-2.3.0-SNAPSHOT-bin.zip')
<re.Match object; span=(0, 31), match='systemds-2.3.0-SNAPSHOT-bin.zip'>
>>> resobj1.match('systemds-2.3.0-bin.zip')
<re.Match object; span=(0, 22), match='systemds-2.3.0-bin.zip'>
```
Resolves bug with 8df051fedfd60c9613c6aa4158af0c1b89968f48
References:
[1] https://docs.python.org/3/library/fnmatch.html
[2] https://docs.python.org/3/using/cmdline.html#command-line
=> [MINOR] Python `SYSTEMDS_BIN` update for all the version types

src/main/java/org/apache/sysds/runtime/transform/encode/ColumnEncoder.java, src/main/java/org/apache/sysds/runtime/transform/encode/ColumnEncoderDummycode.java, src/main/java/org/apache/sysds/runtime/transform/encode/ColumnEncoderPassThrough.java
This patch extends the loop-tiling logic for the apply phases
to sparse matrices as well.
=> [SYSTEMDS-3236] Cache-friendly Apply phase for sparse target matrix

src/test/java/org/apache/sysds/test/functions/iogen/FrameGenerateReaderCSVTest.java, src/test/java/org/apache/sysds/test/functions/iogen/FrameGenerateReaderLibSVMTest.java, src/test/java/org/apache/sysds/test/functions/iogen/GenerateReaderFrameTest.java, src/test/java/org/apache/sysds/test/functions/iogen/GenerateReaderMatrixTest.java, src/test/java/org/apache/sysds/test/functions/iogen/MatrixGenerateReaderCSVTest.java, src/test/java/org/apache/sysds/test/functions/iogen/MatrixGenerateReaderLibSVMTest.java, src/test/java/org/apache/sysds/test/functions/iogen/MatrixGenerateReaderMatrixMarketTest.java
This commit makes "iogen" directory in "/test/scripts/functions" path when we don't have it.
=> [SYSTEMDS-3240] Fix IOGEN test path if the iogen directory doesn't exist

dev/release/README.md
- Add software and credential requirements
=> [SYSTEMDS-3187] Add documentation for the release scripts

.github/workflows/docker-cd.yml
Use [metadata action](https://github.com/docker/metadata-action)
to parameterize tags, to accommodate tagged releases.
=> [SYSTEMDS-3268] Publish Docker images on schedule

docs/site/docker.md
For now, the basic doc with only using `apache/systemds:nightly` tag.
=> [SYSTEMDS-3270][DOCS] Docker usage documentation

.github/workflows/docker-testImage.yml
Adds a new docker-testImage.yml to allow manual initialization of building
our test image. This allows us to update the image used in our github
actions if for instance a new R package is added.
This commit also slightly modify the docker action to also build
the python image, when the default night cpu build is made.
=> [SYSTEMDS-3271] Publish docker test image when requested

src/main/java/org/apache/sysds/conf/ConfigurationManager.java, src/main/java/org/apache/sysds/conf/DMLConfig.java, src/main/java/org/apache/sysds/runtime/controlprogram/federated/FederatedData.java, src/main/java/org/apache/sysds/runtime/controlprogram/federated/FederatedWorkerHandler.java, src/main/java/org/apache/sysds/runtime/controlprogram/paramserv/FederatedPSControlThread.java, src/test/config/SystemDS-MultiTenant-config.xml, src/test/config/SystemDS-config.xml, src/test/java/org/apache/sysds/test/AutomatedTestBase.java, src/test/scripts/functions/federated/codegen/SystemDS-config-codegen.xml, src/test/scripts/functions/federated/io/SSLConfig.xml
This commit adds two things to the federated handler.
1. A timeout (default unlimited) that is enabled for tests to
ensure that the tests finish instead of having a controller waiting
infinitely on a crashed worker.
2. Log output of errors on the workers to enable debugging if you have
access to the worker process output. This ensures that if there is sensitive
information in the error message it is contained to the worker but still
logged.
=> [SYSTEMDS-3273] Federated Timeout

docs/site/builtins-reference.md, scripts/builtin/impurityMeasures.dml, src/main/java/org/apache/sysds/common/Builtins.java, src/test/java/org/apache/sysds/test/functions/builtin/part1/BuiltinImpurityMeasuresTest.java, src/test/scripts/functions/builtin/impurityMeasures.dml
This builtin computes the measure of impurity for the given dataset based on the passed method. The current version expects the target vector to contain only 0 or 1 values and categorical data to be positive integers. Additionally, the builtin expects a row vector R to denote which features are continuous and which are categorical. In case of continuous features, the current implementation applies equal width binning.
It returns a row vector with gini gain or information gain for each feature. In both cases, the higher the gain, the better the split.
=> [SYSTEMDS-3184] Builtin for computing information gain using entropy and gini

pom.xml
Use a `protobuf.version` consistent naming across the pom definition.
=> [MINOR] Add `protobuf` parameter for consistency

src/main/java/org/apache/sysds/lops/BinaryM.java, src/main/java/org/apache/sysds/lops/FunctionCallCP.java, src/main/java/org/apache/sysds/lops/compile/linearization/ILinearize.java, src/main/java/org/apache/sysds/runtime/controlprogram/context/SparkExecutionContext.java, src/main/java/org/apache/sysds/runtime/instructions/spark/ZipmmSPInstruction.java, src/test/java/org/apache/sysds/test/functions/async/MaxParallelizeOrderTest.java, src/test/java/org/apache/sysds/test/functions/async/PrefetchRDDTest.java, src/test/scripts/functions/async/MaxParallelizeOrder5.dml, src/test/scripts/functions/async/PrefetchRDD4.dml
This patch fixes bugs in the max_parallelize operator ordering logic, adds extensions such as finding and defining operators with collect for broadcast as triggering Spark roots and an asynchronous Zipmm implementation. This patch as well adds new tests.
=> [SYSTEMDS-3469] Bug fixes, new tests and extensions

docs/_config.yml, src/main/python/docs/source/conf.py, src/main/python/systemds/project_info.py
checklist:
- https://github.com/apache/systemds/blob/main/pom.xml#L28
- https://github.com/apache/systemds/blob/main/src/main/python/systemds/project_info.py#L26
- https://github.com/apache/systemds/blob/main/src/main/python/docs/source/conf.py#L41
- https://github.com/apache/systemds/blob/main/docs/_config.yml#L42
for python project version scheme is 3.2.0-dev or 3.2.0,
for the java project it is 3.2.0-SNAPSHOT or 3.2.0
=> [MINOR] Update next dev version in the project

scripts/builtin/splitBalanced.dml
This commit change the table instruction in split balanced to be performed before the cbind, and move some as.scalar a bit up. This makes it slightly faster, but we need as a future task to improve the split balanced therefore i have added a jira:
https://issues.apache.org/jira/browse/SYSTEMDS-3607
=> [MINOR] Split balanced minor optimization

src/test/java/org/apache/sysds/test/AutomatedTestBase.java, src/test/java/org/apache/sysds/test/functions/federated/multitenant/MultiTenantTestBase.java
This commit adds a timeout on all tests of 1000 seconds. this means in practice that the github actions does not stall for 1.5 hours, if something is wrong.
=> [MINOR] Timeout test

src/main/java/org/apache/sysds/runtime/data/SparseBlockCSR.java, src/main/java/org/apache/sysds/runtime/data/SparseBlockMCSR.java, src/main/java/org/apache/sysds/runtime/data/SparseRow.java
This commit change the internal printing of sparse matrices to print in LIBSVM format. The change happens because I realized that I accidentally made the internal writer print something very close to LIBSVM. I could therefore not help myself not to make a minor refinement to make it LIBSVM.
=> [MINOR] Refine internal sparse printing

src/main/java/org/apache/sysds/runtime/frame/data/FrameBlock.java, src/main/java/org/apache/sysds/runtime/frame/data/columns/ABooleanArray.java, src/main/java/org/apache/sysds/runtime/frame/data/columns/Array.java, src/main/java/org/apache/sysds/runtime/frame/data/columns/CharArray.java, src/main/java/org/apache/sysds/runtime/frame/data/columns/DDCArray.java, src/main/java/org/apache/sysds/runtime/frame/data/columns/DoubleArray.java, src/main/java/org/apache/sysds/runtime/frame/data/columns/FloatArray.java, src/main/java/org/apache/sysds/runtime/frame/data/columns/IntegerArray.java, src/main/java/org/apache/sysds/runtime/frame/data/columns/LongArray.java, src/main/java/org/apache/sysds/runtime/frame/data/columns/OptionalArray.java, src/main/java/org/apache/sysds/runtime/frame/data/columns/RaggedArray.java, src/main/java/org/apache/sysds/runtime/frame/data/columns/StringArray.java, src/main/java/org/apache/sysds/runtime/frame/data/lib/FrameLibApplySchema.java, src/main/java/org/apache/sysds/runtime/frame/data/lib/FrameUtil.java, src/test/java/org/apache/sysds/performance/simple/DetectTypeArray.java, src/test/java/org/apache/sysds/test/component/frame/FrameUtilTest.java, src/test/java/org/apache/sysds/test/component/frame/array/FrameArrayTests.java
This commit refine the detection and selection of float values in the schema detection algorithm located in:
src/main/java/org/apache/sysds/runtime/frame/data/lib/FrameUtil.java
To improve the performance a custom matcher have been made to avoid using regexes if possible, and we try to avoid parsing the float value from the string representation if at all possible. The implementation is not completely fool proof and does not consider many adversarial inputs.
=> [MINOR] Frame Float detection refinement

pom.xml
```bash
mvn --settings ../tmp-settings-nexus.xml -Pdistribution deploy \
-DaltDeploymentRepository=local-temp::default::file:///$PWD/${tmp_repo} \
-Daether.checksums.algorithms='SHA-512,SHA-1,MD5'
```
logs
```
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-common-artifact-filters/3.0.1/maven-common-artifact-filters-3.0.1.jar (61 kB at 1.1 MB/s)
gpg: can't open '/workspaces/j143-systemds/target/systemds-3.2.0-shaded.jar': No such file or directory
gpg: signing failed: No such file or directory
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```
=> [MINOR] copy shaded jar instead of moving

src/test/java/org/apache/sysds/test/functions/iogen/FrameGenerateReaderCustomTest.java, src/test/java/org/apache/sysds/test/functions/iogen/FrameGenerateReaderXMLTest.java, src/test/java/org/apache/sysds/test/functions/iogen/GenerateReaderFrameTest.java, src/test/java/org/apache/sysds/test/functions/iogen/GenerateReaderMatrixTest.java, src/test/java/org/apache/sysds/test/functions/iogen/MatrixGenerateReaderMMTest.java
Hi @corepointer, 
This patch fixed the issues with GIO test cases.
=> [SYSTEMDS-3672] GIO Test Cases false positive

.gitignore, src/main/python/conf/log4j.properties, src/main/python/pre_setup.py, src/main/python/systemds/context/systemds_context.py
This PR change the startup of the python interface to properly use the jar files, and fixes a release issue where if the SYSTEMDS_ROOT is not set the python API did not properly hook into the released jar artifacts.
=> [SYSTEMDS-3687] Python API startup fixes

scripts/builtin/kmeans.dml, src/main/java/org/apache/sysds/hops/TernaryOp.java, src/main/java/org/apache/sysds/runtime/compress/CompressedMatrixBlock.java, src/main/java/org/apache/sysds/runtime/compress/colgroup/ColGroupDDC.java, src/main/java/org/apache/sysds/runtime/compress/lib/CLALibReorg.java, src/main/java/org/apache/sysds/runtime/compress/lib/CLALibRexpand.java, src/main/java/org/apache/sysds/runtime/instructions/cp/CompressionCPInstruction.java, src/main/java/org/apache/sysds/runtime/instructions/cp/CtableCPInstruction.java, src/main/java/org/apache/sysds/runtime/matrix/data/LibMatrixReorg.java, src/test/java/org/apache/sysds/test/component/compress/lib/SeqTableTest.java, src/test/java/org/apache/sysds/test/functions/compress/configuration/CompressBase.java, src/test/java/org/apache/sysds/test/functions/federated/algorithms/FederatedKmeansTest.java
Sebastian Baunsgaard <baunsgaard@apache.org> introduced a new CLALib for Reorg, specifically Transpose
e-strauss <lathancer@gmx.de> applied minor changes:
- a manual rewrite in bultin kmeans script to use argmin (reduced runtime by 18%)
- added new decompressing transpose to DenseBlock from SparseBlock for ColGroupDDC
- fixed bug in sparsity evaluation in decompressed transposed (switch nrow w/ ncol)
- minor bug fix in regarding the cached decompression count
- fixed ctable with seq fuse rewrite fused ctable with given output dim (disaled: performance decrease, need to fix it first)
- fixed null handling in fused seq ctable
- fixed tests which passed for the wrong reason
=> [SYSTEMDS-3824] Decompressing Transpose
